# config/config.yaml
datos:
  train: "data/train"
  val: "data/val"
  img_size: 224

entrenamiento:
  lr: 0.0001 
  batch_size: 16 
  epochs: 20

modelo:
  arquitectura: "squeezenet" #"resnet18", "mobilenet_v2", "efficientnet_b0, squeeznet"
  pretrained: True